version: "3"
services:

  blog:
    build:
      context: .
      dockerfile: /Dockerfile
      target: nginx
    ports: 
      - "8080:80"
    networks:
      - blognet
    volumes:
      - ./:/var/www/html/
    #  - ./logs/nginx:/var/log/nginx/
  php:
    image: php:fpm-alpine
    networks:
      - blognet
    volumes:
      - ./:/var/www/html/
   #   - ./logs/php.log:/var/log/fpm-php.www.log

  mysql:
    image: php:fpm-alpine
    networks:
      - blognet
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: brilliantblog
      MYSQL_USER: brilliant
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 
    volumes:
      - ./docker/mysqlpersistent:/var/lib/mysql
      #- ./dump:/docker-entrypoint-initdb.d

networks:
  blognet: {}
